### PR TITLE
ignore coverage files

### PR DESCRIPTION
**Pull request by jguitar**

### CODE REVIEW

**Comment by turniquette** [comment]
[PullReview stats](https://www.pullreview.com/github/TheTreeHouse/turniquette-api/reviews/pulls/pull_request_34)

**Comment by turniquette** [comment]
[PullReview](https://www.pullreview.com/github/TheTreeHouse/turniquette-api/reviews/pulls/pull_request_34?to_sha=4c9efe227882fea0d65c88216fe671b5be0a7717) **[1 to go.](https://www.pullreview.com/github/TheTreeHouse/turniquette-api/reviews/pulls/pull_request_34)**

**Comment by gponsu** [comment]
:cop: :cop: :cop:  

@jguitar  thank you very much for your help!

I'm a 'toca huevos' but i think that the commit message should start in uppercase  xD

We try to follow this guide to styles to git:

https://github.com/agis-/git-style-guide

**Comment by jguitar** [comment]
Sorry, I was too busy and I couldn't rename the commit message.
But, I like _toca huevos_ people. Rules and standards are good practices.

**Pull request merged**
